ARG version
FROM almalinux:${version:-8}
#CMD [ "ping", "-c5", "google.com" ]
ARG course=Docker
ARG company=amazon
RUN echo "couse:${course} & company:${company}"
CMD [ "sleep", "100"]
#CMD [ "google.com" ]
#ENTRYPOINT [ "ping", "-c5" ]